function JKFLIPFLOP () {


	var scs_m = [scicos_diagram(version="scicos4.2",props=scicos_params(wpar=[600,450,0,0,600,450],Title=["JKFLIPFLOP"],tol=[0.0001;0.000001;1.000E-10;100001;0;0;0],tf=60,context=" ",void1=[],options=tlist(["scsopt","3D","Background","Link","ID","Cmap"],list(%t,33),[8,1],[1,5],list([5,1],[4,1]),[0.8,0.8,0.8]),void2=[],void3=[],doc=list()))];
	scs_m.objs.push(scicos_block(gui="DOLLAR_m",graphics=scicos_graphics(orig=[299.96961,261.584],sz=[40,40],flip=%f,theta=0,exprs=["int8(0)";"1"],pin=7,pout=5,pein=[],peout=[],gr_i=[],id="",in_implicit="E",out_implicit="E"),model=scicos_model(sim=list("dollar4_m",4),in=1,in2=1,intyp=5,out=1,out2=1,outtyp=5,evtin=[],evtout=[],state=[],dstate=[],odstate=list(int8(0)),rpar=[],ipar=[],opar=list(),blocktype="d",firing=[],dep_ut=[%f,%f],label="",nzcross=0,nmode=0,equations=list()),doc=list()));

	var scs_m_1 = [scicos_diagram(version="scicos4.2",props=scicos_params(wpar=[600,450,0,0,600,450],Title=["EDGE_TRIGGER","./"],tol=[0.0001;0.000001;1.000E-10;100001;0;0;0],tf=30,context=" ",void1=[],options=tlist(["scsopt","3D","Background","Link","ID","Cmap"],list(%t,33),[8,1],[1,5],list([5,1],[4,1]),[0.8,0.8,0.8]),void2=[],void3=[],doc=list()))];
	scs_m_1.objs.push(scicos_block(gui="EDGETRIGGER",graphics=scicos_graphics(orig=[288.58631,257.1131],sz=[60,40],flip=%t,theta=0,exprs="-1",pin=5,pout=3,pein=[],peout=[],gr_i=[],id="",in_implicit="E",out_implicit="E"),model=scicos_model(sim=list("edgetrig",4),in=1,in2=[],intyp=1,out=1,out2=[],outtyp=1,evtin=[],evtout=[],state=[],dstate=0,odstate=list(),rpar=[],ipar=-1,opar=list(),blocktype="c",firing=[],dep_ut=[%t,%f],label="",nzcross=1,nmode=0,equations=list()),doc=list()));
	scs_m_1.objs.push(scicos_block(gui="IFTHEL_f",graphics=scicos_graphics(orig=[388.28869,247.1131],sz=[60,60],flip=%t,theta=0,exprs=["0";"0"],pin=3,pout=[],pein=[],peout=[7;0],gr_i=[],id="",in_implicit="E",out_implicit=[]),model=scicos_model(sim=list("ifthel",-1),in=1,in2=[],intyp=1,out=[],out2=1,outtyp=[],evtin=[],evtout=[1;1],state=[],dstate=[],odstate=list(),rpar=[],ipar=[],opar=list(),blocktype="l",firing=[-1,-1],dep_ut=[%t,%f],label="",nzcross=0,nmode=0,equations=list()),doc=list()));
	scs_m_1.objs.push(scicos_link({xx: new ScilabDouble([357.15774),yy: new ScilabDouble([277.1131),thick: new ScilabDouble([0,0]),ct: new ScilabDouble([1,1]),from: new ScilabDouble([1,1,0]),to: new ScilabDouble([2,1,1])}));
	scs_m_1.objs.push(scicos_block(gui="IN_f",graphics=scicos_graphics(orig=[240.01488,267.1131],sz=[20,20],flip=%t,theta=0,exprs="1",pin=[],pout=5,pein=[],peout=[],gr_i=[],id="",in_implicit=[],out_implicit="E"),model=scicos_model(sim="input",in=[],in2=[],intyp=1,out=-1,out2=[],outtyp=1,evtin=[],evtout=[],state=[],dstate=[],odstate=list(),rpar=[],ipar=1,opar=list(),blocktype="c",firing=[],dep_ut=[%f,%f],label="",nzcross=0,nmode=0,equations=list()),doc=list()));
	scs_m_1.objs.push(scicos_link({xx: new ScilabDouble([260.01488),yy: new ScilabDouble([277.1131),thick: new ScilabDouble([0,0]),ct: new ScilabDouble([1,1]),from: new ScilabDouble([4,1,0]),to: new ScilabDouble([1,1,1])}));
	scs_m_1.objs.push(scicos_block(gui="CLKOUTV_f",graphics=scicos_graphics(orig=[398.28869,181.39881],sz=[20,30],flip=%t,theta=0,exprs="1",pin=[],pout=[],pein=7,peout=[],gr_i=[],id="",in_implicit=[],out_implicit=[]),model=scicos_model(sim="output",in=[],in2=[],intyp=1,out=[],out2=[],outtyp=1,evtin=1,evtout=[],state=[],dstate=[],odstate=list(),rpar=[],ipar=1,opar=list(),blocktype="d",firing=[],dep_ut=[%f,%f],label="",nzcross=0,nmode=0,equations=list()),doc=list()));
	scs_m_1.objs.push(scicos_link({xx: new ScilabDouble([408.28869),yy: new ScilabDouble([241.39881),thick: new ScilabDouble([0,0]),ct: new ScilabDouble([5,-1]),from: new ScilabDouble([2,1,0]),to: new ScilabDouble([6,1,1])}));
	scs_m.objs.push(scicos_block(gui="EDGE_TRIGGER",graphics=scicos_graphics(orig=[292.52452,323.54888],sz=[60,40],flip=%t,theta=0,exprs=[],pin=14,pout=[],pein=[],peout=8,gr_i=[],id="",in_implicit="E",out_implicit=[]),model=scicos_model(sim="csuper",in=-1,in2=[],intyp=1,out=[],out2=[],outtyp=1,evtin=[],evtout=1,state=[],dstate=[],odstate=list(),rpar=scs_m_1,ipar=[],opar=list(),blocktype="h",firing=[],dep_ut=[%f,%f],label="",nzcross=0,nmode=0,equations=list()),doc=list()));
	scs_m.objs.push(scicos_block(gui="LOGIC",graphics=scicos_graphics(orig=[302.79613,202.52782],sz=[40,40],flip=%t,theta=0,exprs=["[0;1;1;1;0;0;1;0]";"0"],pin=[5;16;18],pout=4,pein=8,peout=[],gr_i=[],id="",in_implicit=["E";"E";"E"],out_implicit="E"),model=scicos_model(sim=list("logic",4),in=[1;1;1],in2=[1;1;1],intyp=[5;5;5],out=1,out2=1,outtyp=5,evtin=1,evtout=[],state=[],dstate=[],odstate=list(),rpar=[],ipar=[],opar=list(int8([0;1;1;1;0;0;1;0])),blocktype="c",firing=%f,dep_ut=[%t,%f],label="",nzcross=0,nmode=0,equations=list()),doc=list()));
	scs_m.objs.push(scicos_link({xx: new ScilabDouble([351.36756),yy: new ScilabDouble([222.52782),thick: new ScilabDouble([0,0]),ct: new ScilabDouble([1,1]),from: new ScilabDouble([3,1,0]),to: new ScilabDouble([10,1,1])}));
	scs_m.objs.push(scicos_link({xx: new ScilabDouble([291.39818),yy: new ScilabDouble([281.584),thick: new ScilabDouble([0,0]),ct: new ScilabDouble([1,1]),from: new ScilabDouble([1,1,0]),to: new ScilabDouble([3,1,1])}));
	scs_m.objs.push(scicos_block(gui="SPLIT_f",graphics=scicos_graphics(orig=[368.82793,243.45067],sz=[0.3333333,0.3333333],flip=%t,theta=0,exprs=[],pin=11,pout=[7;20],pein=[],peout=[],gr_i=[],id="",in_implicit="E",out_implicit=["E";"E";"E"]),model=scicos_model(sim="lsplit",in=-1,in2=[],intyp=1,out=[-1;-1;-1],out2=[],outtyp=1,evtin=[],evtout=[],state=[],dstate=[],odstate=list(),rpar=[],ipar=[],opar=list(),blocktype="c",firing=[],dep_ut=[%t,%f],label="",nzcross=0,nmode=0,equations=list()),doc=list()));
	scs_m.objs.push(scicos_link({xx: new ScilabDouble([368.82793),yy: new ScilabDouble([243.45067),thick: new ScilabDouble([0,0]),ct: new ScilabDouble([1,1]),from: new ScilabDouble([6,1,0]),to: new ScilabDouble([1,1,1])}));
	scs_m.objs.push(scicos_link({xx: new ScilabDouble([322.52452),yy: new ScilabDouble([317.8346),thick: new ScilabDouble([0,0]),ct: new ScilabDouble([5,-1]),from: new ScilabDouble([2,1,0]),to: new ScilabDouble([3,1,1])}));
	scs_m.objs.push(scicos_block(gui="LOGICAL_OP",graphics=scicos_graphics(orig=[377.63217,159.25363],sz=[60,40],flip=%t,theta=0,exprs=["1";"5";"5";"0"],pin=12,pout=22,pein=[],peout=[],gr_i=[],id="",in_implicit="E",out_implicit="E"),model=scicos_model(sim=list("logicalop_i8",4),in=-1,in2=-2,intyp=5,out=-1,out2=-2,outtyp=5,evtin=[],evtout=[],state=[],dstate=[],odstate=list(),rpar=[],ipar=[5;0],opar=list(),blocktype="c",firing=[],dep_ut=[%t,%f],label="",nzcross=0,nmode=0,equations=list()),doc=list()));
	scs_m.objs.push(scicos_block(gui="SPLIT_f",graphics=scicos_graphics(orig=[368.82793;223.06473],sz=[0.3333333,0.3333333],flip=%t,theta=0,exprs=[],pin=4,pout=[11;12],pein=[],peout=[],gr_i=[],id="",in_implicit="E",out_implicit=["E";"E";"E"]),model=scicos_model(sim="lsplit",in=-1,in2=[],intyp=1,out=[-1;-1;-1],out2=[],outtyp=1,evtin=[],evtout=[],state=[],dstate=[],odstate=list(),rpar=[],ipar=[],opar=list(),blocktype="c",firing=[],dep_ut=[%t,%f],label="",nzcross=0,nmode=0,equations=list()),doc=list()));
	scs_m.objs.push(scicos_link({xx: new ScilabDouble([368.82793),yy: new ScilabDouble([223.06473),thick: new ScilabDouble([0,0]),ct: new ScilabDouble([1,1]),from: new ScilabDouble([10,1,0]),to: new ScilabDouble([6,1,1])}));
	scs_m.objs.push(scicos_link({xx: new ScilabDouble([368.82793),yy: new ScilabDouble([223.06473),thick: new ScilabDouble([0,0]),ct: new ScilabDouble([1,1]),from: new ScilabDouble([10,2,0]),to: new ScilabDouble([9,1,1])}));
	scs_m.objs.push(scicos_block(gui="IN_f",graphics=scicos_graphics(orig=[243.95309,333.54888],sz=[20,20],flip=%t,theta=0,exprs="2",pin=[],pout=14,pein=[],peout=[],gr_i=[],id="",in_implicit=[],out_implicit="E"),model=scicos_model(sim="input",in=[],in2=[],intyp=1,out=-1,out2=[],outtyp=-1,evtin=[],evtout=[],state=[],dstate=[],odstate=list(),rpar=[],ipar=2,opar=list(),blocktype="c",firing=[],dep_ut=[%f,%f],label="",nzcross=0,nmode=0,equations=list()),doc=list()));
	scs_m.objs.push(scicos_link({xx: new ScilabDouble([263.95309),yy: new ScilabDouble([343.54888),thick: new ScilabDouble([0,0]),ct: new ScilabDouble([1,1]),from: new ScilabDouble([13,1,0]),to: new ScilabDouble([2,1,1])}));
	scs_m.objs.push(scicos_block(gui="IN_f",graphics=scicos_graphics(orig=[254.2247,212.52782],sz=[20,20],flip=%t,theta=0,exprs="1",pin=[],pout=16,pein=[],peout=[],gr_i=[],id="",in_implicit=[],out_implicit="E"),model=scicos_model(sim="input",in=[],in2=[],intyp=1,out=-1,out2=[],outtyp=-1,evtin=[],evtout=[],state=[],dstate=[],odstate=list(),rpar=[],ipar=1,opar=list(),blocktype="c",firing=[],dep_ut=[%f,%f],label="",nzcross=0,nmode=0,equations=list()),doc=list()));
	scs_m.objs.push(scicos_link({xx: new ScilabDouble([274.2247),yy: new ScilabDouble([222.52782),thick: new ScilabDouble([0,0]),ct: new ScilabDouble([1,1]),from: new ScilabDouble([15,1,0]),to: new ScilabDouble([3,2,1])}));
	scs_m.objs.push(scicos_block(gui="IN_f",graphics=scicos_graphics(orig=[254.2247,202.52782],sz=[20,20],flip=%t,theta=0,exprs="3",pin=[],pout=18,pein=[],peout=[],gr_i=[],id="",in_implicit=[],out_implicit="E"),model=scicos_model(sim="input",in=[],in2=[],intyp=1,out=-1,out2=[],outtyp=-1,evtin=[],evtout=[],state=[],dstate=[],odstate=list(),rpar=[],ipar=3,opar=list(),blocktype="c",firing=[],dep_ut=[%f,%f],label="",nzcross=0,nmode=0,equations=list()),doc=list()));
	scs_m.objs.push(scicos_link({xx: new ScilabDouble([274.2247),yy: new ScilabDouble([212.52782),thick: new ScilabDouble([0,0]),ct: new ScilabDouble([1,1]),from: new ScilabDouble([17,1,0]),to: new ScilabDouble([3,3,1])}));
	scs_m.objs.push(scicos_block(gui="OUT_f",graphics=scicos_graphics(orig=[388.82793,233.45067],sz=[20,20],flip=%t,theta=0,exprs="1",pin=20,pout=[],pein=[],peout=[],gr_i=[],id="",in_implicit="E",out_implicit=[]),model=scicos_model(sim="output",in=-1,in2=[],intyp=-1,out=[],out2=[],outtyp=1,evtin=[],evtout=[],state=[],dstate=[],odstate=list(),rpar=[],ipar=1,opar=list(),blocktype="c",firing=[],dep_ut=[%f,%f],label="",nzcross=0,nmode=0,equations=list()),doc=list()));
	scs_m.objs.push(scicos_link({xx: new ScilabDouble([368.82793),yy: new ScilabDouble([243.45067),thick: new ScilabDouble([0,0]),ct: new ScilabDouble([1,1]),from: new ScilabDouble([6,2,0]),to: new ScilabDouble([19,1,1])}));
	scs_m.objs.push(scicos_block(gui="OUT_f",graphics=scicos_graphics(orig=[466.2036,169.25363],sz=[20,20],flip=%t,theta=0,exprs="2",pin=22,pout=[],pein=[],peout=[],gr_i=[],id="",in_implicit="E",out_implicit=[]),model=scicos_model(sim="output",in=-1,in2=[],intyp=-1,out=[],out2=[],outtyp=1,evtin=[],evtout=[],state=[],dstate=[],odstate=list(),rpar=[],ipar=2,opar=list(),blocktype="c",firing=[],dep_ut=[%f,%f],label="",nzcross=0,nmode=0,equations=list()),doc=list()));
	scs_m.objs.push(scicos_link({xx: new ScilabDouble([446.2036),yy: new ScilabDouble([179.25363),thick: new ScilabDouble([0,0]),ct: new ScilabDouble([1,1]),from: new ScilabDouble([9,1,0]),to: new ScilabDouble([21,1,1])}));

	var model = scicos_model();
	model.sim = new ScilabString(["csuper"]);
	model.in = new ScilabDouble([1],[1],[1]);
	model.in2 = new ScilabDouble([1],[1],[1]);
	model.out = new ScilabDouble([1],[1]);
	model.out2 = new ScilabDouble([1],[1]);
	model.intyp = new ScilabDouble([5,1,5]);
	model.outtyp = new ScilabDouble([5,5]);
	model.blocktype = new ScilabString(["h"]);
	model.firing = new ScilabBoolean([false]);
	model.dep_ut = new ScilabBoolean([true,false]);
	model.rpar=scs_m;

	var gr_i = [];
	this.x=new standard_define(new ScilabDouble([2,3]),model,[],gr_i);
}
